language: cpp

os:
  - linux
  - osx
osx_image: xcode9.1

compiler:
  - gcc
  - clang

branches:
  only:
  - master
  - development
  - "/feature.*/"
  - "/hotfix.*/"

addons:
  apt:
    packages:
      - python3
      - g++-7
    sources: &sources
      - ubuntu-toolchain-r-test

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

script:
  - ls
  - python3 --version
  - gcc --version
